### ISSUE TITLE
any chance it can be run from an usb stick? 

### ISSUE THREAD

**Issue by mihai-satmarean** [mendhak/automated-wsl-dev-setup#1]
Thanks for making this available!
Great work on automating it, and very nice blog post.
Do you think it can be installed on an usb stick in the manner of portable apps, and be used with any windows capable computer?
Best regards,
Mihai

**Comment by mendhak** [comment]
Hello there. You're asking about WSL itself, right (not these scripts)? I don't think you can do this because running a dev setup like this has two parts.  One part is enabling WSL features on the Windows computer, and the second is the distro itself (like Ubuntu or Fedora).  The _distro_ is somewhat portable, you can have the distro and carry it around with you and `--export` and `--import` it on any machine where WSL is enabled.  But in all cases, you'll need to enable WSL each time.  So it's never going to be a plug and play type deal.  [See here also](https://old.reddit.com/r/bashonubuntuonwindows/comments/drp4fr/is_it_possible_to_run_a_version_of_linux_in_wsl/).  I've never done this myself so no idea if it works.  

If you're looking for something more portable, what about Git for Windows, on its [releases page](https://github.com/git-for-windows/git/releases/tag/v2.30.0.windows.2) I can see a portable version. It's very limited as you get a basic bash environment but not Ubuntu/WSL itself.

**Comment by mihai-satmarean** [comment]
Hi.
thanks again for the work on this script.
Actually, with running some part of your script about wsl config, and the import export, I was able to make a "portable" linux distribution on an usb stick.
It is a bit slow to init, and it needs to put its expanded files somewhere, but it servers my PoC.
Closing this.
